# Generated by Django 3.0.8 on 2020-08-09 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_owner', models.IntegerField()),
                ('dst_owner', models.IntegerField()),
                ('value_in_rial', models.IntegerField()),
                ('remittance_currency', models.CharField(max_length=40)),
                ('remittance_value', models.IntegerField()),
                ('settlement_type', models.CharField(choices=[('1', 'تک حواله ای'), ('2', 'چند حواله ای')], default='1', max_length=50)),
                ('judge_vote', models.CharField(choices=[('1', 'معامله انجام شده است'), ('2', 'معامله انجام نشده است')], max_length=50)),
                ('expire_date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='JudgeProfile',
            fields=[
                ('national_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('bank_account_id', models.IntegerField(primary_key=True, serialize=False)),
                ('owner_type', models.CharField(choices=[('1', 'صراف'), ('2', 'وارد کننده'), ('3', 'صادر کننده')], default='1', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('national_code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('owners', models.ManyToManyField(to='myapp.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('owner', models.IntegerField()),
                ('otherside_owner', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('1', 'واریزی'), ('2', 'پرداختی')], default='1', max_length=50)),
                ('value', models.IntegerField()),
                ('operator_type', models.CharField(choices=[('1', 'کاربر'), ('2', 'سیستم')], default='1', max_length=50)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Subcontract',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dst_owner', models.IntegerField()),
                ('value_in_rial', models.IntegerField()),
                ('remittance_value', models.IntegerField()),
                ('judge_vote', models.CharField(choices=[('1', 'معامله انجام شده است'), ('2', 'معامله انجام نشده است')], max_length=50)),
                ('expire_date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Contract')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='judge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.JudgeProfile'),
        ),
        migrations.CreateModel(
            name='AuthProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
