# Generated by Django 3.0.8 on 2020-08-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('1', 'در انتظار تایید طرف دیگر قرارداد'), ('2', 'در انتظار داوری'), ('3', 'داوری شده است')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subcontract',
            name='status',
            field=models.CharField(choices=[('1', 'در انتظار تایید طرف دیگر قرارداد'), ('2', 'در انتظار داوری'), ('3', 'داوری شده است')], max_length=20),
        ),
    ]
